[package]
name = "annotate-output"
version = "0.1.0"
authors = ["Daniel Lin <ephemient@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
nix = "0.19"
